name: Deploy and Run Script

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Script with Firebase Secret
      run: |
        echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" > .env

    - name: Run Script with Groq Secret
      run: |
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env
