# name: NodeJS with Webpack

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       pages: write

#     env:
#       FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
#       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

#     steps:
#     - uses: actions/checkout@v4

#     - name: Use Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: 20.15

#     - name: Build
#       run: |
#         npm install
#         npm run build

#     - name: Zip artifact for deployment
#       run: zip release.zip ./* -r

#     - name: Upload artifact for deployment job
#       uses: actions/upload-artifact@v4
#       with:
#         name: github-pages
#         path: release.zip

name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write

    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.15

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Zip artifact for deployment
      run: zip -r release.zip ./build

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages

    - name: Set up GitHub Pages
      uses: actions/configure-pages@v4
      with:
        build_dir: ./build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_DEPLOY_KEY }}
        publish_dir: ./build
        keep_files: false
